AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/PredicateMethod:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  Enabled: false
